# Database Configuration Settings
# Generated by qwen2.5-coder:7b model test

# Database connection parameters
DATABASE_CONFIG = {
    "host": "localhost",
    "port": 5432,
    "database": "app_db",
    "username": "app_user",
    "password": "secure_password",
    "ssl_mode": "require",
    "connection_timeout": 30,
    "max_connections": 20
}

# Redis cache configuration
REDIS_CONFIG = {
    "host": "localhost",
    "port": 6379,
    "db": 0,
    "password": None,
    "decode_responses": True
}

# Application settings
APP_CONFIG = {
    "debug": False,
    "log_level": "INFO",
    "secret_key": "your-secret-key-here",
    "session_timeout": 3600
}

def get_database_url():
    """Generate database URL from configuration."""
    return f"postgresql://{DATABASE_CONFIG['username']}:{DATABASE_CONFIG['password']}@{DATABASE_CONFIG['host']}:{DATABASE_CONFIG['port']}/{DATABASE_CONFIG['database']}"

def get_redis_url():
    """Generate Redis URL from configuration."""
    return f"redis://{REDIS_CONFIG['host']}:{REDIS_CONFIG['port']}/{REDIS_CONFIG['db']}"